export const USER_ENDPOINTS = {
  agentdata: `/v1/agents`,
  getUsers: `/v1/users`,
  getCustomer: `/v1/users`,
  getKnowledge: `/v1/knowledge_base`,
  getvoicecall: `/v1/voicecalls/`,
  getaction: `/v1/actions/`,
  getassist: `/v1/voiceassistants`,
  login: `/v1/login`,
  makecall: `/v1/voicecalls`,
  createChat: `/v1/ai/chat`,
  addIntent: `/v1/voiceassistants`,
  getmodel: `/v1/ai/models`,
  profile: "/v1/me",
  forgotpassword: "/v1/user/forgot_password",
  Otpverification: "/v1/user/new_password",
  register: "/v1/register",
  Oauth: "/v1/google/signin?redirect_uri=https://contactswing.com/login",
};
